[package]
name = "key-value-store"
version = "0.1.0"
edition = "2021"

[dependencies]
array-init = "0.1.0"
serde_json = "1.0"
serde = { version = "1.0.210", features = ["derive"] }

[lib]
name = "lib"
path = "src/lib.rs"
